
#define FIBRE_ENABLE_SERVER F_RUNTIME_CONFIG
#define FIBRE_ENABLE_CLIENT F_RUNTIME_CONFIG
#define FIBRE_ENABLE_EVENT_LOOP 0
#define FIBRE_ENABLE_TCP_SERVER_BACKEND 0
#define FIBRE_ENABLE_TCP_CLIENT_BACKEND 0
#define FIBRE_ENABLE_CAN_ADAPTER 1
