#ifndef __STATIC_EXPORTS_HPP
#define __STATIC_EXPORTS_HPP

#include <fibre/fibre.hpp>

#if FIBRE_ENABLE_SERVER
namespace fibre {

// Forward declarations for autogenerated code in static_exports.cpp
template<typename T> ServerInterfaceId get_interface_id();

extern ServerFunctionDefinition static_server_function_table[];
extern size_t n_static_server_functions;
//extern ServerInterfaceDefinition static_server_interface_table[];

extern ServerObjectDefinition static_server_object_table[];
extern size_t n_static_server_objects;

}
#endif

#endif // __STATIC_EXPORTS_HPP
